# Test your FastAPI endpoints

GET http://127.0.0.1:8002/validate_user?username=johndoe1&password=12345
Accept: application/json

###

POST http://127.0.0.1:8002/create_user
Content-Type: application/json

{
  "username": "johndoe2",
  "password": "12345",
  "email": "johndoe2@email.com"
}



